import React from 'react';
import {cleanup, render} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom/extend-expect';
import {axe} from 'jest-axe';
import 'jest-axe/extend-expect';

import InputHue from '../components/InputHue';

test('renders correctly', () => {
  const {container} = render(<InputHue />);
  expect(container).toMatchInlineSnapshot(`
    <div>
      <fieldset>
        <legend>
          Hue
        </legend>
        <label
          for="red"
        >
          <input
            id="red"
            name="hue"
            type="radio"
            value="0"
          />
          Red
        </label>
        <label
          for="vermilion"
        >
          <input
            id="vermilion"
            name="hue"
            type="radio"
            value="15"
          />
          Vermilion
        </label>
        <label
          for="orange"
        >
          <input
            id="orange"
            name="hue"
            type="radio"
            value="30"
          />
          Orange
        </label>
        <label
          for="amber"
        >
          <input
            id="amber"
            name="hue"
            type="radio"
            value="45"
          />
          Amber
        </label>
        <label
          for="yellow"
        >
          <input
            id="yellow"
            name="hue"
            type="radio"
            value="60"
          />
          Yellow
        </label>
        <label
          for="yellowishGreen"
        >
          <input
            id="yellowishGreen"
            name="hue"
            type="radio"
            value="75"
          />
          Yellowish Green
        </label>
        <label
          for="chartreuse"
        >
          <input
            id="chartreuse"
            name="hue"
            type="radio"
            value="90"
          />
          Chartreuse
        </label>
        <label
          for="leafGreen"
        >
          <input
            id="leafGreen"
            name="hue"
            type="radio"
            value="105"
          />
          Leaf Green
        </label>
        <label
          for="green"
        >
          <input
            id="green"
            name="hue"
            type="radio"
            value="120"
          />
          Green
        </label>
        <label
          for="cobaltGreen"
        >
          <input
            id="cobaltGreen"
            name="hue"
            type="radio"
            value="135"
          />
          Cobalt Green
        </label>
        <label
          for="springGreen"
        >
          <input
            id="springGreen"
            name="hue"
            type="radio"
            value="150"
          />
          Spring Green
        </label>
        <label
          for="turquoisGreen"
        >
          <input
            id="turquoisGreen"
            name="hue"
            type="radio"
            value="165"
          />
          Turquois Green
        </label>
        <label
          for="cyan"
        >
          <input
            id="cyan"
            name="hue"
            type="radio"
            value="180"
          />
          Cyan
        </label>
        <label
          for="ceruleanBlue"
        >
          <input
            id="ceruleanBlue"
            name="hue"
            type="radio"
            value="195"
          />
          Cerulean Blue
        </label>
        <label
          for="azure"
        >
          <input
            id="azure"
            name="hue"
            type="radio"
            value="210"
          />
          Azure
        </label>
        <label
          for="cobaltBlue"
        >
          <input
            id="cobaltBlue"
            name="hue"
            type="radio"
            value="225"
          />
          Cobalt Blue
        </label>
        <label
          for="blue"
        >
          <input
            id="blue"
            name="hue"
            type="radio"
            value="240"
          />
          Blue
        </label>
        <label
          for="hyacinth"
        >
          <input
            id="hyacinth"
            name="hue"
            type="radio"
            value="255"
          />
          Hyacinth
        </label>
        <label
          for="violet"
        >
          <input
            id="violet"
            name="hue"
            type="radio"
            value="270"
          />
          Violet
        </label>
        <label
          for="purple"
        >
          <input
            id="purple"
            name="hue"
            type="radio"
            value="285"
          />
          Purple
        </label>
        <label
          for="magenta"
        >
          <input
            id="magenta"
            name="hue"
            type="radio"
            value="300"
          />
          Magenta
        </label>
        <label
          for="reddishPurple"
        >
          <input
            id="reddishPurple"
            name="hue"
            type="radio"
            value="315"
          />
          Reddish Purple
        </label>
        <label
          for="rose"
        >
          <input
            id="rose"
            name="hue"
            type="radio"
            value="330"
          />
          Rose
        </label>
        <label
          for="carmine"
        >
          <input
            id="carmine"
            name="hue"
            type="radio"
            value="345"
          />
          Carmine
        </label>
      </fieldset>
    </div>
  `);
});

test('is accessible', async () => {
  const {container} = render(<InputHue />);
  const results = await axe(container);
  expect(results).toHaveNoViolations();
  cleanup();
});
