import React from 'react';
import {cleanup, fireEvent, render} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom/extend-expect';
import {axe} from 'jest-axe';
import 'jest-axe/extend-expect';

import ChromaScale from '../../components/ChromaScale';

afterEach(() => {
  jest.clearAllMocks();
});

let container, getByLabelText;
beforeEach(() => {
  return ({container, getByLabelText} = render(<ChromaScale />));
});

test('renders correctly', () => {
  expect(container).toMatchInlineSnapshot(`
    <div>
      <svg
        aria-labelledby="chromaScale"
        viewBox="0 0 32 255"
      >
        <title
          id="chromaScale"
        >
          Chroma scale
        </title>
        <defs>
          <lineargradient
            id="linearGradient-1"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#0000FF"
            />
            <stop
              offset="100%"
              stop-color="#1F1FFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-2"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#2020FF"
            />
            <stop
              offset="100%"
              stop-color="#3F3FFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-3"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#4040FF"
            />
            <stop
              offset="100%"
              stop-color="#5F5FFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-4"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#6060FF"
            />
            <stop
              offset="100%"
              stop-color="#7F7FFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-5"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#8080FF"
            />
            <stop
              offset="100%"
              stop-color="#9F9FFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-6"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#A0A0FF"
            />
            <stop
              offset="100%"
              stop-color="#BFBFFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-7"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#C0C0FF"
            />
            <stop
              offset="100%"
              stop-color="#DFDFFF"
            />
          </lineargradient>
          <lineargradient
            id="linearGradient-8"
            x1="50%"
            x2="50%"
            y1="0%"
            y2="100%"
          >
            <stop
              offset="0%"
              stop-color="#E0E0FF"
            />
            <stop
              offset="100%"
              stop-color="#FFFFFF"
            />
          </lineargradient>
        </defs>
        <g
          fill="none"
          stroke="none"
        >
          <rect
            fill="url(#linearGradient-1)"
            height="31"
            width="32"
            x="0"
            y="0"
          />
          <rect
            fill="url(#linearGradient-2)"
            height="31"
            width="32"
            x="0"
            y="32"
          />
          <rect
            fill="url(#linearGradient-3)"
            height="31"
            width="32"
            x="0"
            y="64"
          />
          <rect
            fill="url(#linearGradient-4)"
            height="31"
            width="32"
            x="0"
            y="96"
          />
          <rect
            fill="url(#linearGradient-5)"
            height="31"
            width="32"
            x="0"
            y="128"
          />
          <rect
            fill="url(#linearGradient-6)"
            height="31"
            width="32"
            x="0"
            y="160"
          />
          <rect
            fill="url(#linearGradient-7)"
            height="31"
            width="32"
            x="0"
            y="192"
          />
          <rect
            fill="url(#linearGradient-8)"
            height="31"
            width="32"
            x="0"
            y="224"
          />
        </g>
      </svg>
    </div>
  `);
});

test('is accessible', async () => {
  const results = await axe(container);
  expect(results).toHaveNoViolations();
  cleanup();
});
